{% set provider = "opensearch" %}
{% set goname = "github.com/opensearch-project/terraform-provider-"+provider.lower() %}
{% set version = "2.1.0" %}

{% set name = goname.split('/')[-1] %}

{% set plugin_dir = os.sep.join(["plugins", "registry.terraform.io", "hashicorp", provider.lower(), version]) %}
{% set x4_plugin = name + '_v' + version %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 83c4b797231e7db1dca8c8236a81267f6bc43c006d4a6aa39261899261713cae

build:
  number: 0
  skip: true  # [win]
  script:
    - go build -v -o {{ target_gobin }}..{{ os.sep }}{{ plugin_dir }}{{ os.sep }}{{ target_goos }}_{{ target_goarch }}{{ os.sep }}{{ x4_plugin }}{{ target_goexe }}
    - go-licenses save --save_path licenses .

requirements:
  build:
    - {{ compiler('go') }} 1.20
    - go-licenses


test:
  requires:
    - terraform >=1

  commands:
    # Create a sample init.tf loading the provider
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [unix]
    - echo provider "{{ provider|lower }}" { version="{{ version }}" } > init.tf    # [win]

    # Initialize
    - terraform init --plugin-dir={{ target_gobin }}..{{ os.sep }}plugins

    # Tests that init was successful
    - test -f .terraform.lock.hcl              # [unix]
    - if not exist .terraform.lock.hcl exit 1  # [win]

    # Test that the provider was not downloaded
    - test ! -f .terraform/plugins/{{ plugin_dir }}/{{ target_goos }}_{{ target_goarch }}/README.md  # [unix]
    - if exist .terraform\plugins\{{ plugin_dir }}\{{ target_goos }}_{{ target_goarch }}/README.md exit 1  # [win]

about:
  home: https://www.terraform.io
  license: Apache-2.0
  license_file:
    - LICENSE
    - licenses/
  summary: The Terraform Opensearch provider
  doc_url: https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs
  dev_url: https://{{ goname }}

extra:
  recipe-maintainers:
    - conda-forge/terraform
    - tp-jssk
